font_size 12.0
dynamic_background_opacity yes
background_opacity 0.8
background_blur 1

window_margin_width 4
window_border_width 2pt
single_window_border_width 2pt

enabled_layouts tall

tab_bar_style powerline
tab_powerline_style slanted

hide_window_decorations no

font_family hack

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME
