Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 24
Gtk/CursorThemeName "Breeze_Light"
Net/SoundThemeName "ocean"
Net/IconThemeName "Breeze Chameleon Dark"
Gtk/FontName "Segoe UI Variable Static Small,  12"
Net/ThemeName "Breeze-Dark"

